CREATE TABLE DESTINATIONS (
    ID              BIGINT AUTO_INCREMENT  PRIMARY KEY,
    SENT            BOOLEAN,
    DELIVERED       BOOLEAN,
    NOTIFICATION_ID   BIGINT,
    DESTINATION     VARCHAR(500)
);

CREATE TABLE NOTIFICATIONS (
    ID                BIGINT AUTO_INCREMENT  PRIMARY KEY,
    CREATE_DATE       TIMESTAMP,
    SENDING_DATE      TIMESTAMP,
    TITLE             VARCHAR(500),
    TEXT              VARCHAR(4000),
    NEED_DELIVERY     BOOLEAN,
    BROAD_CAST        BOOLEAN,
    STATE             VARCHAR(50), -- NULL,SENDING,SENT,DELIVERED
    CREATOR           VARCHAR(500)
);

CREATE TABLE CONFIRMATIONS (
    ID                BIGINT AUTO_INCREMENT  PRIMARY KEY,
    USER              VARCHAR(500),
    NOTIFICATION_ID   BIGINT,
    DECISION          VARCHAR(50),
    DECISION_DATE     TIMESTAMP
);