INSERT INTO NOTIFICATIONS(CREATE_DATE,SENDING_DATE,TITLE,TEXT,NEED_DELIVERY,BROAD_CAST,CREATOR)
VALUES(CURRENT_TIMESTAMP ,CURRENT_TIMESTAMP +100,'Winter is coming','You should remember this, The north remembers',FALSE,TRUE,'NED_STARK');

INSERT INTO NOTIFICATIONS(ID,CREATE_DATE,SENDING_DATE,TITLE,TEXT,NEED_DELIVERY,BROAD_CAST,CREATOR)
VALUES(1000,{ts '2012-09-17 18:47:52.69'},{ts '2012-09-17 18:47:52.69'},'Hear Me Roar','A Lanister always pays his debt!',FALSE,TRUE,'TYWIN_LANISTER');
INSERT INTO CONFIRMATIONS(USER,NOTIFICATION_ID,DECISION,DECISION_DATE)
VALUES('ROBBERT_BARATHEON',1000,'CONFIRMED',CURRENT_TIMESTAMP);
INSERT INTO CONFIRMATIONS(USER,NOTIFICATION_ID,DECISION,DECISION_DATE)
VALUES('JOHN_SNOW',1000,'CONFIRMED',CURRENT_TIMESTAMP);

INSERT INTO NOTIFICATIONS(ID,CREATE_DATE,SENDING_DATE,TITLE,TEXT,NEED_DELIVERY,BROAD_CAST,CREATOR)
VALUES(1001,{ts '2012-09-17 18:47:52.69'},{ts '2012-09-17 18:47:52.69'},'Hear Me Roar','A Lanister always pays his debt!',FALSE,TRUE,'TYWIN_LANISTER');
INSERT INTO CONFIRMATIONS(USER,NOTIFICATION_ID,DECISION,DECISION_DATE)
VALUES('ROBBERT_BARATHEON',1001,'CONFIRMED',CURRENT_TIMESTAMP);
INSERT INTO CONFIRMATIONS(USER,NOTIFICATION_ID,DECISION,DECISION_DATE)
VALUES('JOHN_SNOW',1001,'CONFIRMED',CURRENT_TIMESTAMP);
INSERT INTO CONFIRMATIONS(USER,NOTIFICATION_ID,DECISION,DECISION_DATE)
VALUES('CERCI_LANISTER',1001,'CONFIRMED',CURRENT_TIMESTAMP);

INSERT INTO NOTIFICATIONS(ID,CREATE_DATE,SENDING_DATE,TITLE,TEXT,NEED_DELIVERY,BROAD_CAST,CREATOR)
VALUES(1002,{ts '2012-09-17 18:47:52.69'},{ts '2012-09-17 18:47:52.69'},'Hear Me Roar','A Lanister always pays his debt!',FALSE,TRUE,'TYWIN_LANISTER');
INSERT INTO CONFIRMATIONS(USER,NOTIFICATION_ID,DECISION,DECISION_DATE)
VALUES('ROBBERT_BARATHEON',1002,'CONFIRMED',CURRENT_TIMESTAMP);



